#!/usr/bin/env bash

# Nerd Font icons. Requires Maple Mono NF or another Nerd Font.
export APPLE="󰀵"
export FRONT_APP="󰣆"
export CPU="󰍛"
export MEMORY="󰘚"
export CLOCK="󰥔"
export BATTERY_100="󰁹"
export BATTERY_75="󰂁"
export BATTERY_50="󰁾"
export BATTERY_25="󰁻"
export BATTERY_0="󰂎"
export BATTERY_CHARGING="󰂄"
export VOLUME_100="󰕾"
export VOLUME_66="󰖀"
export VOLUME_33="󰕿"
export VOLUME_0="󰝟"
export WIFI="󰖩"
export WIFI_OFF="󰖪"
export API="󰒋"
export DOCKER="󰡨"
export INPUT="󰌌"
export GIT_BRANCH="󰘬"
export SEPARATOR="󰇘"
